[package]
name = "rocket"
version = "0.1.0"
authors = ["kirinnee <kirinnee97@gmail.com>"]
edition = "2018"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "async" }
